var annotated =
[
    [ "Comparable", "class_comparable.html", "class_comparable" ],
    [ "Course", "class_course.html", "class_course" ],
    [ "CourseReader", "class_course_reader.html", "class_course_reader" ],
    [ "DataCreator", "class_data_creator.html", "class_data_creator" ],
    [ "FileReader", "class_file_reader.html", "class_file_reader" ],
    [ "FileReaderFactory", "class_file_reader_factory.html", "class_file_reader_factory" ],
    [ "FileWriter", "class_file_writer.html", "class_file_writer" ],
    [ "LinearScoreCalculator", "class_linear_score_calculator.html", "class_linear_score_calculator" ],
    [ "Prof", "class_prof.html", "class_prof" ],
    [ "ProfInfo", "class_prof_info.html", "class_prof_info" ],
    [ "ProfReader", "class_prof_reader.html", "class_prof_reader" ],
    [ "Reader", "class_reader.html", "class_reader" ],
    [ "ReaderFactory", "class_reader_factory.html", "class_reader_factory" ],
    [ "Room", "class_room.html", "class_room" ],
    [ "RoomReader", "class_room_reader.html", "class_room_reader" ],
    [ "Schedule", "class_schedule.html", "class_schedule" ],
    [ "ScheduleGenerator", "class_schedule_generator.html", "class_schedule_generator" ],
    [ "ScoreCalculator", "class_score_calculator.html", "class_score_calculator" ],
    [ "TestCourse", "class_test_course.html", "class_test_course" ],
    [ "TestCourseReader", "class_test_course_reader.html", "class_test_course_reader" ],
    [ "TestProf", "class_test_prof.html", null ],
    [ "WeightedScoreCalculator", "class_weighted_score_calculator.html", "class_weighted_score_calculator" ],
    [ "Writer", "class_writer.html", "class_writer" ]
];